"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { LocationPicker } from "@/components/location-picker";
type User={name:string;email:string}; type Group={code:string;title:string;place:string;when:string}; type Point={latitude:number;longitude:number};

export default function Home(){
  const [user,setUser]=useState<User|null>(null),[mode,setMode]=useState<"login"|"signup">("login"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[title,setTitle]=useState(""),[when,setWhen]=useState(""),[place,setPlace]=useState(""),[target,setTarget]=useState<Point|null>(null),[code,setCode]=useState(""),[groups,setGroups]=useState<Group[]>([]),[view,setView]=useState<"create"|"list">("create"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{const raw=localStorage.getItem("momentum-session");if(raw)try{setUser(JSON.parse(raw))}catch{localStorage.removeItem("momentum-session")}},[]);
  const loadGroups=useCallback(async(account:User)=>{const r=await fetch(`/api/groups?email=${encodeURIComponent(account.email)}`,{cache:"no-store"});const d=await r.json();setGroups(d.groups||[])},[]);
  useEffect(()=>{if(user)loadGroups(user)},[user,loadGroups]);
  const enter=(c:string)=>{if(!user)return;localStorage.setItem("momentum-user",user.name);localStorage.setItem("momentum-group",c);location.href=`/chat?group=${c}`};
  const auth=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:mode,name,email,password})});const d=await r.json();if(!r.ok)throw Error(d.error);localStorage.setItem("momentum-session",JSON.stringify(d.user));setUser(d.user)}catch(e){setError(e instanceof Error?e.message:"처리 실패")}finally{setBusy(false)}};
  const create=async(e:FormEvent)=>{e.preventDefault();if(!user)return;setBusy(true);setError("");try{const r=await fetch("/api/groups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,when,place,latitude:target?.latitude,longitude:target?.longitude,ownerEmail:user.email})});const d=await r.json();if(!r.ok)throw Error(d.error);enter(d.code)}catch(e){setError(e instanceof Error?e.message:"저장 실패")}finally{setBusy(false)}};
  const join=async(e:FormEvent)=>{e.preventDefault();if(!user)return;const groupCode=code.trim().toUpperCase();if(!groupCode)return setError("초대 코드를 입력해 주세요.");setBusy(true);setError("");try{const r=await fetch(`/api/groups/${groupCode}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"join",email:user.email})});const d=await r.json();if(!r.ok)throw Error(d.error);setCode("");await loadGroups(user);setView("list")}catch(e){setError(e instanceof Error?e.message:"그룹에 참여하지 못했어요.")}finally{setBusy(false)}};
  if(!user)return <main className="shell"><nav className="topbar"><span className="brand"><span className="brand-mark">M</span> Momentum</span></nav><section className="hero glass"><h1>약속을<br/><em>지키는 시작.</em></h1><p>친구와 약속을 만들고 함께 준비하세요.</p></section><section className="section-heading"><h2>{mode==="login"?"로그인":"회원가입"}</h2><button className="mode-switch" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"가입하기":"로그인"}</button></section><form className="form-card glass" onSubmit={auth}>{mode==="signup"&&<label>이름<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>이메일<input value={email} type="email" onChange={e=>setEmail(e.target.value)} required/></label><label>비밀번호<input value={password} type="password" onChange={e=>setPassword(e.target.value)} required/></label><button className="primary-button" disabled={busy}>{mode==="login"?"로그인":"계정 만들기"}<span>→</span></button></form>{error&&<p className="form-error">{error}</p>}</main>;
  return <main className="dashboard"><aside className="sidebar"><div className="brand"><span className="brand-mark">M</span> Momentum</div><div className="side-nav"><button className={view==="create"?"active":""} onClick={()=>setView("create")}>＋ 그룹 작성</button><button className={view==="list"?"active":""} onClick={()=>setView("list")}>▤ 그룹 목록</button></div><button className="account-button" onClick={()=>{localStorage.removeItem("momentum-session");setUser(null)}}><span>{user.name[0]}</span> 로그인</button></aside><section className="dashboard-content"><header><p>안녕하세요, {user.name}님</p><h1>{view==="create"?"새로운 약속 만들기":"내 약속 목록"}</h1></header>{view==="create"?<><section className="hero glass compact"><div className="eyebrow">모바일 GPS 지원</div><h2>현재 위치에서 약속 장소를<br/><em>터치로 지정하세요.</em></h2></section><form className="form-card glass create-form" onSubmit={create}><label>약속 이름<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>약속 시간<input value={when} onChange={e=>setWhen(e.target.value)} type="datetime-local" required/></label><label>만날 장소<input value={place} onChange={e=>setPlace(e.target.value)} required/></label><LocationPicker value={target} onChange={setTarget}/><button className="primary-button" disabled={busy}>그룹 작성하기 <span>→</span></button></form></>:<><form className="tip glass join-form list-join" onSubmit={join}><input value={code} onChange={e=>setCode(e.target.value)} placeholder="초대 코드 입력" maxLength={6}/><button disabled={busy}>참여하기</button></form><section className="group-grid">{groups.length?groups.map(g=><button className="group-card glass" onClick={()=>enter(g.code)} key={g.code}><span>초대 코드 · {g.code}</span><strong>{g.title}</strong><small>{new Date(g.when).toLocaleString("ko-KR")}<br/>{g.place}</small></button>):<section className="tip glass">직접 만들거나 참여한 약속이 아직 없어요.</section>}</section></>}{error&&<p className="form-error">{error}</p>}</section></main>;
}
