"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

export default function Home() {
  const [name, setName] = useState(""); const [title, setTitle] = useState(""); const [when, setWhen] = useState(""); const [place, setPlace] = useState(""); const [code, setCode] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const enter = (groupCode: string) => { localStorage.setItem("momentum-user", name.trim()); localStorage.setItem("momentum-group", groupCode); location.href = "/chat"; };
  const create = async (e: FormEvent) => { e.preventDefault(); if (!name.trim()) return setError("내 이름을 입력해 주세요."); setBusy(true); setError(""); try { const res = await fetch("/api/groups", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, when, place }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); enter(data.code); } catch (e) { setError(e instanceof Error ? e.message : "약속을 만들지 못했어요."); } finally { setBusy(false); } };
  const join = async (e: FormEvent) => { e.preventDefault(); if (!name.trim()) return setError("내 이름을 입력해 주세요."); const groupCode = code.trim().toUpperCase(); if (!groupCode) return setError("초대 코드를 입력해 주세요."); setBusy(true); setError(""); try { const res = await fetch(`/api/groups/${groupCode}`); if (!res.ok) { const data = await res.json(); throw new Error(data.error); } enter(groupCode); } catch (e) { setError(e instanceof Error ? e.message : "그룹에 참여하지 못했어요."); } finally { setBusy(false); } };
  return <main className="shell"><nav className="topbar"><span className="brand"><span className="brand-mark">M</span> Momentum</span></nav><section className="hero glass"><div className="eyebrow"><span className="live-dot" /> 실제 약속 그룹</div><h1>늦지 않게,<br /><em>우리 같이 움직이자.</em></h1><p>약속을 만들고 친구에게 초대 코드를 보내세요. 같은 그룹에서 준비 상황과 대화를 함께 볼 수 있어요.</p></section><section className="section-heading"><div><p>시작하기</p><h2>내 정보</h2></div></section><section className="routine-list glass form-card"><label>내 이름<input value={name} onChange={e => setName(e.target.value)} placeholder="예: 민지" maxLength={20} /></label></section><section className="section-heading"><div><p>새 약속</p><h2>그룹 만들기</h2></div></section><form className="routine-list glass form-card" onSubmit={create}><label>약속 이름<input value={title} onChange={e => setTitle(e.target.value)} placeholder="예: 서연이 생일 모임" required /></label><label>약속 시간<input value={when} onChange={e => setWhen(e.target.value)} type="datetime-local" required /></label><label>만날 장소<input value={place} onChange={e => setPlace(e.target.value)} placeholder="예: 성수역 3번 출구" required /></label><button className="primary-button" disabled={busy}>{busy ? "만드는 중…" : "약속 만들기"} <span>→</span></button></form><section className="section-heading"><div><p>초대받았나요?</p><h2>그룹 참여하기</h2></div></section><form className="tip glass join-form" onSubmit={join}><input value={code} onChange={e => setCode(e.target.value)} placeholder="6자리 초대 코드" maxLength={6} /><button disabled={busy}>참여</button></form>{error && <p className="form-error" role="alert">{error}</p>}<p className="login-note">데이터는 안전한 Vercel Blob 저장소에 보관됩니다.</p></main>;
}
